### ISSUE TITLE
region_data.json

### ISSUE THREAD

**Issue by yi-dan** [ASKanse/Nuclei-Segmentation#1]
Hello, may I know what region_data.json is referring to? i couldnt find this file inside the dataset.

**Comment by ASKanse** [comment]
Hi, Its a file containing the COCO style conversion of the dataset.
Let me know if you need its code.

**Comment by yi-dan** [comment]
> Hi, Its a file containing the COCO style conversion of the dataset.
> Let me know if you need its code.

It would be very helpful if you can share it with me. Thankss a lot!

**Comment by ASKanse** [comment]
I have added the "jsonwriter.py" file
